### ISSUE TITLE
Compilation fails

### ISSUE THREAD

**Issue by vortex314** [le1ca/generic_median#1]
Looking for a MedianFilter for my robot project  I was glad to find your solution. However compilation seems to fail. Any suggestions ?

----------Building project:[ akkaEsp32 - Debug ]----------
Toolchain path: /home/lieven/esp/xtensa-esp32-elf/bin/xtensa-esp32-elf-gcc
Toolchain version: crosstool-ng-1.22.0-80-g6c4433a

CXX build/Controller/Controller.o
In file included from /home/lieven/workspace/akkaEsp32/components/Controller/Controller.h:9:0,
                 from /home/lieven/workspace/akkaEsp32/components/Controller/Controller.cpp:1:
/home/lieven/workspace/akkaEsp32/components/Controller/MedianFilter.h: In instantiation of 'MedianFilter<T, S>::MedianFilter() [with T = int; int S = 5]':
/home/lieven/workspace/akkaEsp32/components/Controller/Controller.cpp:13:39:   required from here
/home/lieven/workspace/akkaEsp32/components/Controller/MedianFilter.h:50:27: error: 'MedianFilter<int, 5>::m_med' will be initialized after [-Werror=reorder]
     T m_buf[S], m_tmp[S], m_med;
                           ^
/home/lieven/workspace/akkaEsp32/components/Controller/MedianFilter.h:49:16: error:   'int MedianFilter<int, 5>::m_cnt' [-Werror=reorder]
     int m_idx, m_cnt;
                ^
/home/lieven/workspace/akkaEsp32/components/Controller/MedianFilter.h:11:5: error:   when initialized here [-Werror=reorder]
     MedianFilter()
     ^
cc1plus: warning: unrecognized command line option '-Wno-frame-address'
cc1plus: some warnings being treated as errors
/home/lieven/esp/esp-idf/make/component_wrapper.mk:289: recipe for target 'Controller.o' failed
make[1]: *** [Controller.o] Error 1
/home/lieven/esp/esp-idf/make/project.mk:582: recipe for target 'component-Controller-build' failed
make: *** [component-Controller-build] Error 2
====5 errors, 3 warnings====

**Comment by vortex314** [comment]
Ok, rearranged the MedianFilter.h code a bit and works fine now. Nice to see the output of the filter now giving rock-steady values. Updated code : https://github.com/vortex314/akkaEsp32/blob/master/components/Controller/MedianFilter.h

**Comment by tmick0** [comment]
Thanks for the find. I never tried to compile with warnings on, I guess. If you'd like to submit a PR, go ahead, otherwise I'll make the change shortly.

**Comment by vortex314** [comment]
Thanks for the feedback. I'm using this for ADC measuring and stabilization of the output in a remote controller. https://vortex314.blogspot.com/2019/06/step-2-remote-controller-via-akka.html
The ESP32 is basically generating a lot of noise in the ADC conversion. https://github.com/espressif/esp-idf/issues/164
The Medianfilter greatly helped in this.
